### ISSUE TITLE
Adding reviewers to proposals and returning to proposal invitation

### ISSUE THREAD

**Issue by SofieW** [ubiquitypress/rua#435] opened 2016-05-03 08:19 UTC
Hi,
When you add new reviewers to a proposal that is not previously registered in the system, you have to go back to the dashboard in order to return to the proposal you were working on in order to send the invitation after adding the new user details.

It would be most convenient to add reviewers as you go along rather than having to add them before you start the invitation process. Hope we can connect the two functions later on.
Many thanks.
/Sofie.

**Comment by twakeford** [comment] 2016-05-03 08:59
I believe that this is a duplicate of #398

**Closed** 2016-05-03 09:11 UTC
